name: "Build Kubernetes E2E test binary"

on:
  workflow_dispatch:
    inputs:
      KUBERNETES_REPOSITORY:
        description: "Kubernetes repository used to build the E2E test binary"
        default: "https://github.com/e2e-win/kubernetes.git"
      KUBERNETES_BRANCH:
        description: "Kubernetes branch used to build the E2E test binary"
        default: "master"

jobs:
  build-e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kubernetes
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.KUBERNETES_REPOSITORY }}
          ref: ${{ github.event.inputs.KUBERNETES_BRANCH }}

      - name: Build E2E test binary
        run: make WHAT="test/e2e/e2e.test" KUBE_BUILD_PLATFORMS="linux/amd64"
        env:
          CGO_ENABLED: "0"

      - name: Upload E2E test binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: e2e.test
          path: _output/local/bin/linux/amd64/e2e.test
